run:
  deadline: 5m
  go: 1.18

linter-settings:
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
  - revive
  - goconst
  - gofmt
  - goimports
  - misspell
  - unparam
  disable:
  - deadcode

issues:
  exclude-use-default: false
  exclude-rules:
  - path: _test.go
    linters:
    - errcheck
